class TokenType
  EOS_TOK = 'EOS_TOK'
  FEATURE_TOK = 'FEATURE_TOK'
  ID_TOK= 'ID_TOK'
  IS_TOK = 'IS_TOK'
  DO_TOK = 'DO_TOK'
  ASSIGN_TOK = 'ASSIGN_TOK'
  CONST_TOK = 'CONST_TOK'
  PRINT_TOK = 'PRINT_TOK'
  LPARAN_TOK = 'LPARAN_TOK'
  RPARAN_TOK = 'RPARAN_TOK'
  END_TOK = 'END_TOK'
end
